export {
  provideRouter as provideClientRouter,
  provideRouter,
  Router,
  ROUTE,
  ROUTE_CONTEXT,
  RouterLink,
  RouterOutlet,
  route,
  redirectRoute,
  layout,
  lazyLayout,
  lazyRoute,
  routeSlot,
  routesFor,
  type NavigationTree,
  type NamedRouteDefinition,
  type ResolvedNavigationConfiguration,
  type RouteResolution,
  type RouteResolutionContext,
  type RouterOptions,
} from '@epikodelabs/waypoint';
export { type RouterRevalidationOptions } from '@epikodelabs/waypoint';
